<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="HistoryCollectorServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/HistoryCollectorServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/HistoryCollectorServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://history.esb.javaitzen/">
    <import location="DemoEJB2/wsdl/HistoryCollectorService.wsdl" namespace="http://history.esb.javaitzen/"/>
    <plnk:partnerLinkType name="HistoryCollectorLinkType">
        <plnk:role name="HistoryCollectorRole" portType="ns:HistoryCollector"/>
    </plnk:partnerLinkType>
</definitions>

