<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="DataCollectorServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/DataCollectorServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/DataCollectorServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://data.esb.javaitzen/">
    <import location="DemoEJB1/wsdl/DataCollectorService.wsdl" namespace="http://data.esb.javaitzen/"/>
    <plnk:partnerLinkType name="DataCollectorLinkType">
        <plnk:role name="DataCollectorRole" portType="ns:DataCollector"/>
    </plnk:partnerLinkType>
</definitions>

