<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="DemoESBServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/DemoESBServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/DemoESBServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://esb.javaitzen/">
    <import location="DemoESBService.wsdl" namespace="http://esb.javaitzen/"/>
    <plnk:partnerLinkType name="DemoESBLinkType">
        <plnk:role name="DemoESBRole" portType="ns:DemoESB"/>
    </plnk:partnerLinkType>
</definitions>

